name: android build scripts

on:
  push:
    branches:
      - development
      - main
    paths:
      - ".github/workflows/android-build-scripts.yml"
      - "android/**"
      - "!android/README.md"
      - "scripts/**"
      - "tools/**"
      - "android.sh"
  pull_request:
    branches:
      - development
      - main
    paths:
      - ".github/workflows/android-build-scripts.yml"
      - "android/**"
      - "!android/README.md"
      - "scripts/**"
      - "tools/**"
      - "android.sh"

jobs:
  build-main-on-linux:
    name: android main on linux
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ndk-version: ["r22b-linux-x86_64", "r25b-linux"]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: set up adopt jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "17"
      - name: prerequisites
        run: sudo apt-get install autoconf automake libtool pkg-config curl git doxygen nasm cmake gcc gperf texinfo yasm bison autogen wget autopoint meson ninja-build ragel groff gtk-doc-tools libtasn1-bin
      - name: prerequisites 2
        run: ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --uninstall "cmake;3.10.2.4988404" "cmake;3.18.1"
      - name: upgrade meson
        run: pip install meson --upgrade
      - name: set up android ndk
        run: |
          curl -s "https://dl.google.com/android/repository/android-ndk-${{ matrix.ndk-version }}.zip" -o ndk.zip
          unzip -q -o ndk.zip -d .ndk
          echo "ANDROID_NDK_ROOT=$PWD/.ndk/$(ls .ndk)" >> $GITHUB_ENV
      - name: run the build script
        run: ./android.sh -l --enable-gpl --enable-lame --enable-android-media-codec --enable-android-zlib --disable-arm-v7a --disable-x86
      - name: print build logs
        if: ${{ always() }}
        run: cat build.log
      - name: print ffbuild logs
        if: ${{ failure() }}
        run: "[[ -f ./src/ffmpeg/ffbuild/config.log ]] && tail -50 ./src/ffmpeg/ffbuild/config.log"
      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: android/ffmpeg-kit-android-lib/build/outputs/aar/ffmpeg-kit-release.aar
